name: Release

on:
  repository_dispatch:
    types: [release-trigger]
  push:
    branches:
      - main
      - staging
      - "release/**"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: GIT checkout
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git checkout main
          git fetch --tags

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: NPM Install
        run: |
          npm install
      - name: Find Version
        run: |
          echo "GIT_TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: Make GitHub Release
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          CHANGELOG=$(./script/most_recent_changelog.sh)
          node .script/make-github-release/bin/make-github-release.js release --owner "${{ github.repository_owner }}" --repo "${{ github.event.repository.name }}" --text "${CHANGELOG}" --auth "${{ secrets.GITHUB_TOKEN }}"
      - name: Build
        run: |
          npm run build
          ls -la dist
